-- INSERT PERFIL --
INSERT INTO PERFIL (ID_PERFIL, NOME) VALUES (1, 'ADMINISTRADOR');
INSERT INTO PERFIL (ID_PERFIL, NOME) VALUES (2, 'MEDICO');
INSERT INTO PERFIL (ID_PERFIL, NOME) VALUES (3, 'ATENDENTE');
INSERT INTO PERFIL (ID_PERFIL, NOME) VALUES (4, 'CREDENCIADO');

-- -----------------------------------------------------------------------------
-- -----------------------------------------------------------------------------

-- INSERT LOGIN --
INSERT INTO LOGIN (ID_LOGIN, ID_PERFIL, ACESSO_SISTEMA, LOGIN, SENHA, EMAIL)
VALUES (1, 1, 2, 'ADM.01', '1234', 'ADM_01@TESTE.COM');
INSERT INTO LOGIN (ID_LOGIN, ID_PERFIL, ACESSO_SISTEMA, LOGIN, SENHA, EMAIL)
VALUES (2, 2, 1, 'MED.01', '1234', 'MED_01@TESTE.COM');
INSERT INTO LOGIN (ID_LOGIN, ID_PERFIL, ACESSO_SISTEMA, LOGIN, SENHA, EMAIL)
VALUES (3, 3, 1, 'ATE.01', '1234', 'ATE_01@TESTE.COM');
INSERT INTO LOGIN (ID_LOGIN, ID_PERFIL, ACESSO_SISTEMA, LOGIN, SENHA, EMAIL)
VALUES (4, 4, 1, 'CRED.01', '1234', 'CRED_01@TESTE.COM');