-- INSERT PERFIL --
INSERT INTO PERFIL (ID_PERFIL, NOME) VALUES (1, 'ADMINISTRADOR');
INSERT INTO PERFIL (ID_PERFIL, NOME) VALUES (2, 'MEDICO');
INSERT INTO PERFIL (ID_PERFIL, NOME) VALUES (3, 'ATENDENTE');
INSERT INTO PERFIL (ID_PERFIL, NOME) VALUES (4, 'CREDENCIADO');

-- -----------------------------------------------------------------------------
-- -----------------------------------------------------------------------------

-- INSERT LOGIN --
INSERT INTO LOGIN (ID_PERFIL, ACESSO_SISTEMA, LOGIN, SENHA, EMAIL)
VALUES (1, 2, 'ADM.01', '1234', 'ADM_01@TESTE.COM');
INSERT INTO LOGIN (ID_PERFIL, ACESSO_SISTEMA, LOGIN, SENHA, EMAIL)
VALUES (2, 1, 'MED.01', '1234', 'MED_01@TESTE.COM');
INSERT INTO LOGIN (ID_PERFIL, ACESSO_SISTEMA, LOGIN, SENHA, EMAIL)
VALUES (3, 1, 'ATE.01', '1234', 'ATE_01@TESTE.COM');
INSERT INTO LOGIN (ID_PERFIL, ACESSO_SISTEMA, LOGIN, SENHA, EMAIL)
VALUES (4, 1, 'CRED.01', '1234', 'CRED_01@TESTE.COM');

-- -----------------------------------------------------------------------------
-- -----------------------------------------------------------------------------

-- INSERT ESPECIALIDADE --
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Acupuntura');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Alergia e Imunologia');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Anestesiologia');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Angiologia');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Cancerologia');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Cardiologia');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Cirurgia Cardiovascular');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Cirurgia da MÃ£o');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Cirurgia de CabeÃ§a e PescoÃ§o');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Cirurgia do Aparelho Digestivo');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Cirurgia Geral');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Cirurgia PediÃ¡trica');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Cirurgia PlÃ¡stica');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Cirurgia Vascular');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('ClÃ­nica MÃ©dica');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Coloproctologia');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Dermatologia');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Endocrinologia e Metabologia');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Endoscopia');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Gastroenterologia');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('GenÃ©tica MÃ©dica');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Geriatria');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Ginecologia e ObstetrÃ­cia');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Hematologia e Hemoterapia');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Homeopatia');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Infectologia');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Mastologia');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Medicina de FamÃ­lia e Comunidade');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Medicina do Trabalho');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Medicina de TrÃ¡fego');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Medicina Esportiva');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Medicina FÃ­sica e ReabilitaÃ§Ã£o');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Medicina Intensiva');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Medicina Legal e PerÃ­cia MÃ©dica');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Medicina Nuclear');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Medicina Preventiva e Social');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Neurocirurgia');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Neurologia');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Nutrologia');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Oftalmologia');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Ortopedia e Traumatologia');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Otorrinolaringologia');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Patologia');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Patologia ClÃ­nica/Medicina Laboratorial');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Pediatria');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Pneumologia');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Psiquiatria');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Radiologia e DiagnÃ³stico por Imagem');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Radioterapia');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Reumatologia');
INSERT INTO ESPECIALIDADE (NOME) VALUES ('Urologia');

-- -----------------------------------------------------------------------------
-- -----------------------------------------------------------------------------

-- INSERT CREDENCIADO --
INSERT INTO CREDENCIADO (ID_LOGIN, NOME, CPF, NASCIMENTO, ENDERECO, CEP, BAIRRO, CIDADE, ESTADO, TELEFONE, CELULAR, CONVENIO)
VALUES (4, 'TESTE_01', '123.456.789-00', '1997-05-26', 'RUA TESTE_01', '12345-678', 'BAIRRO TESTE_01', 'CIDADE TESTE_01', 'Piaui', '(00)1234-5678', '(00)91234-5678', 'S');
INSERT INTO CREDENCIADO (ID_LOGIN, NOME, CPF, NASCIMENTO, ENDERECO, CEP, BAIRRO, CIDADE, ESTADO, TELEFONE, CELULAR, CONVENIO)
VALUES (4, 'TESTE_02', '123.456.789-00', '2010-09-15', 'RUA TESTE_02', '12345-678', 'BAIRRO TESTE_02', 'CIDADE TESTE_02', 'Rio de Janeiro', '(00)1234-5678', '(00)91234-5678', 'N');
INSERT INTO CREDENCIADO (ID_LOGIN, NOME, CPF, NASCIMENTO, ENDERECO, CEP, BAIRRO, CIDADE, ESTADO, TELEFONE, CELULAR, CONVENIO)
VALUES (4, 'TESTE_03', '123.456.789-00', '2019-02-21', 'RUA TESTE_03', '12345-678', 'BAIRRO TESTE_03', 'CIDADE TESTE_03', 'Sao Paulo', '(00)1234-5678', '(00)91234-5678', 'S');

-- -----------------------------------------------------------------------------
-- -----------------------------------------------------------------------------

-- INSERT CLINICA --
INSERT INTO CLINICA (ID_LOGIN, CNPJ, NOME, ENDERECO, CEP, BAIRRO, CIDADE, ESTADO, TELEFONE, RESPONSAVEL, CPF_RESPONSAVEL)
VALUES (1, '12.123.123/1234-12', 'TESTE_01', 'RUA TESTE_01', '12345-123', 'BAIRRO TESTE_01', 'CIDADE TESTE_01', 'Amapa', '(12)1234-1234', 'RESP TESTE_01', '123.123.123-12');
INSERT INTO CLINICA (ID_LOGIN, CNPJ, NOME, ENDERECO, CEP, BAIRRO, CIDADE, ESTADO, TELEFONE, RESPONSAVEL, CPF_RESPONSAVEL)
VALUES (1, '12.123.123/1234-12', 'TESTE_02', 'RUA TESTE_02', '12345-123', 'BAIRRO TESTE_02', 'CIDADE TESTE_02', 'Amapa', '(12)1234-1234', 'RESP TESTE_02', '123.123.123-12');
INSERT INTO CLINICA (ID_LOGIN, CNPJ, NOME, ENDERECO, CEP, BAIRRO, CIDADE, ESTADO, TELEFONE, RESPONSAVEL, CPF_RESPONSAVEL)
VALUES (1, '12.123.123/1234-12', 'TESTE_03', 'RUA TESTE_03', '12345-123', 'BAIRRO TESTE_03', 'CIDADE TESTE_03', 'Amapa', '(12)1234-1234', 'RESP TESTE_03', '123.123.123-12');

-- -----------------------------------------------------------------------------
-- -----------------------------------------------------------------------------

-- INSERT ATENDENTE --
INSERT INTO ATENDENTE (ID_LOGIN, ID_CLINICA, NOME, CPF, NASCIMENTO, ENDERECO, CEP, BAIRRO, CIDADE, ESTADO, TELEFONE, CELULAR)
VALUES (3, 1, 'TESTE_01', '123.456.789-00', '1997-05-26', 'RUA TESTE_01', '12345-678', 'BAIRRO TESTE_01', 'CIDADE TESTE_01', 'Piaui', '(00)1234-5678', '(00)91234-5678');
INSERT INTO ATENDENTE (ID_LOGIN, ID_CLINICA, NOME, CPF, NASCIMENTO, ENDERECO, CEP, BAIRRO, CIDADE, ESTADO, TELEFONE, CELULAR)
VALUES (3, 1, 'TESTE_02', '123.456.789-00', '1997-05-26', 'RUA TESTE_02', '12345-678', 'BAIRRO TESTE_02', 'CIDADE TESTE_02', 'Piaui', '(00)1234-5678', '(00)91234-5678');
INSERT INTO ATENDENTE (ID_LOGIN, ID_CLINICA, NOME, CPF, NASCIMENTO, ENDERECO, CEP, BAIRRO, CIDADE, ESTADO, TELEFONE, CELULAR)
VALUES (3, 1, 'TESTE_03', '123.456.789-00', '1997-05-26', 'RUA TESTE_03', '12345-678', 'BAIRRO TESTE_03', 'CIDADE TESTE_03', 'Piaui', '(00)1234-5678', '(00)91234-5678');

-- -----------------------------------------------------------------------------
-- -----------------------------------------------------------------------------

-- INSERT MEDICO --
INSERT INTO MEDICO (ID_LOGIN, ID_CLINICA, NOME, CPF, CRM, NASCIMENTO, ENDERECO, CEP, BAIRRO, CIDADE, ESTADO, TELEFONE, CELULAR)
VALUES (2, 1, 'MEDICO 01', '111.222.333-44', '12345', '1978-11-02', 'ENDERECO MEDICO 01', '11222-333', 'BAIRRO MEDICO 01', 'CIDADE MEDICO 01', 'Rio de Janeiro', '(12)1234-5678', '(12)98765-4321');
INSERT INTO MEDICO (ID_LOGIN, ID_CLINICA, NOME, CPF, CRM, NASCIMENTO, ENDERECO, CEP, BAIRRO, CIDADE, ESTADO, TELEFONE, CELULAR)
VALUES (2, 2, 'MEDICO 02', '111.222.333-44', '12345', '1978-11-02', 'ENDERECO MEDICO 02', '11222-333', 'BAIRRO MEDICO 02', 'CIDADE MEDICO 02', 'Rio de Janeiro', '(12)1234-5678', '(12)98765-4321');
INSERT INTO MEDICO (ID_LOGIN, ID_CLINICA, NOME, CPF, CRM, NASCIMENTO, ENDERECO, CEP, BAIRRO, CIDADE, ESTADO, TELEFONE, CELULAR)
VALUES (2, 3, 'MEDICO 03', '111.222.333-44', '12345', '1978-11-02', 'ENDERECO MEDICO 03', '11222-333', 'BAIRRO MEDICO 03', 'CIDADE MEDICO 03', 'Rio de Janeiro', '(12)1234-5678', '(12)98765-4321');

-- -----------------------------------------------------------------------------
-- -----------------------------------------------------------------------------

-- INSERT ESPECIALIDADE_MEDICO --
INSERT INTO ESPECIALIDADE_MEDICO (ID_ESPECIALIDADE, ID_MEDICO) VALUES (1, 1);
INSERT INTO ESPECIALIDADE_MEDICO (ID_ESPECIALIDADE, ID_MEDICO) VALUES (2, 1);
INSERT INTO ESPECIALIDADE_MEDICO (ID_ESPECIALIDADE, ID_MEDICO) VALUES (3, 1);
INSERT INTO ESPECIALIDADE_MEDICO (ID_ESPECIALIDADE, ID_MEDICO) VALUES (4, 2);
INSERT INTO ESPECIALIDADE_MEDICO (ID_ESPECIALIDADE, ID_MEDICO) VALUES (5, 2);
INSERT INTO ESPECIALIDADE_MEDICO (ID_ESPECIALIDADE, ID_MEDICO) VALUES (6, 2);
INSERT INTO ESPECIALIDADE_MEDICO (ID_ESPECIALIDADE, ID_MEDICO) VALUES (7, 3);
INSERT INTO ESPECIALIDADE_MEDICO (ID_ESPECIALIDADE, ID_MEDICO) VALUES (8, 3);
INSERT INTO ESPECIALIDADE_MEDICO (ID_ESPECIALIDADE, ID_MEDICO) VALUES (9, 3);